Foxglove bridge example
BluEye-Robotics/blueye.sdk pull request #165
Opened 2024-08-27 10:48 UTC by aviggen

**Description**
This PR makes it possible to visualize live telemetry data in Foxglove when connected to a drone. A great addition for students working with the SDK, and also internally for debugging and testing.

The example script `foxglove_bridge_ws.py` is using the drone object from the SDK to connect to the drone, and a web socket server provided by foxglove to forward the messages. With Foxglove it's now possible to subscribe to the web socket server on `ws://localhost:8765` and visualize all the messages coming from the drone.

A new page on how to use it is also added to the docs.

#### Checklist before merging

- [x] Run the tests while connected to a drone
- [x] Update the package version according to [semver](https://semver.org/)

2024-08-27 10:52 UTC, follesoe requested changes

2024-08-27 10:52 UTC, follesoe commented on examples/foxglove_bridge_ws.py
> +        print(f"File descriptor already present: {file_descriptor.name}")
Perhaps remove this else block. Mostly relevant for local debugging, and will probably print a bunch of times as for most cases the files will be added quickly (after iterating the first few messages).

2024-08-27 10:52 UTC, follesoe commented on examples/foxglove_bridge_ws.py
> +            print(f"Registered channel for {name}: {chan_id}")
Also, this for loop is probably not needed in the example script.

2024-08-27 10:52 UTC, follesoe commented on examples/foxglove_bridge_ws.py
> +            print(f"Registered channel for {name}: {chan_id}")
Or perhaps log it as: `print(f"Registered tyopic blueye.protocol.{message_name}")`

2024-08-27 11:16 UTC, follesoe approved these changes

2024-08-27 11:16 UTC, sindrehan requested changes

2024-08-27 11:16 UTC, sindrehan commented on docs/foxglove-bridge.md
> +{{code_from_file("../examples/foxglove_bridge_ws.py", "python")}}
Not sure that it's helpful to include the entire example inline here

2024-08-27 11:16 UTC, sindrehan commented on docs/foxglove-bridge.md
> +3. Run `pip install foxglove_websocket` and `pip install protobuf` in your pyenv.
```suggestion
3. Run `pip install foxglove_websocket`.
```

Protobuf should already be installed with the SDK

2024-08-27 11:16 UTC, sindrehan commented on docs/foxglove-bridge.md
> +3. Run `pip install foxglove_websocket` and `pip install protobuf` in your pyenv.
We could also include the the dependencies as an extra to the sdk package, so that you could run `pip install "blueye.sdk[foxglove]"`, not sure if that's helpful when there's only one extra package.

2024-08-27 11:37 UTC, aviggen commented on docs/foxglove-bridge.md
> +3. Run `pip install foxglove_websocket` and `pip install protobuf` in your pyenv.
Could be nice, where is this configured?

2024-08-27 11:38 UTC, aviggen commented on docs/foxglove-bridge.md
> +{{code_from_file("../examples/foxglove_bridge_ws.py", "python")}}
Agree, I'll change it to a link.

2024-08-30 09:37 UTC, follesoe commented
@aviggen Don't leave this one hanging 😿 😮‍💨

2024-09-02 09:39 UTC, sindrehan approved these changes

2024-09-02 09:40 UTC, merged