Add example showing how to forward position as NMEA over UDP
BluEye-Robotics/blueye.sdk pull request #171
Opened 2024-10-09 11:55 UTC by sindrehan

I'm not really familiar with the NMEA stuff, so would be great if you @aviggen or @haavardsyslak could take a look and see if everything makes sense.

Fixes #170

2024-10-09 13:55 UTC, aviggen commented on examples/nmea_publisher.py
> +    UDP_PORT = 10110
I think we need to broadcast on a different port than we use for NMEA input. Otherwise they will run in a loop.

2024-10-09 13:59 UTC, aviggen commented on examples/nmea_publisher.py
> +    return f"GPGLL,{lat_deg:02d}{lat_min:07.4f},{lat_hemisphere},{lon_deg:03d}{lon_min:07.4f},{lon_hemisphere},{is_valid}"
We could consider GGA is it is more common, but that requires a small format conversion.

2024-10-09 14:24 UTC, aviggen commented on examples/nmea_publisher.py
> +    UDP_PORT = 10110
Should we pick 10111? Cannot see it being used in this list: https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers

2024-10-09 14:30 UTC, aviggen requested changes
We need to change the port, other that than it seems like it will work. Have you been able to test it at all?

2024-10-11 14:00 UTC, sindrehan commented on examples/nmea_publisher.py
> +    UDP_PORT = 10110
ChatGPT suggests that 10111 is sometimes used for TCP messages releated to NMEA, but it's not like there's an official standard here, so I think we'll just go for 10111. It's easy for the user to change it in case it doesn't work in their particular network.

2024-10-11 14:05 UTC, sindrehan commented on examples/nmea_publisher.py
> +    return f"GPGLL,{lat_deg:02d}{lat_min:07.4f},{lat_hemisphere},{lon_deg:03d}{lon_min:07.4f},{lon_hemisphere},{is_valid}"
The GGA message has a bunch of fields for GPS related stuff (number of satellites, fix quality, etc) so I think that would make sense for a message from a GPS receiver, but in our case we don't really get any of that info from the drone, so I think GLL makes more sense.

2024-10-11 14:05 UTC, sindrehan commented on examples/nmea_publisher.py
> +    return f"GPGLL,{lat_deg:02d}{lat_min:07.4f},{lat_hemisphere},{lon_deg:03d}{lon_min:07.4f},{lon_hemisphere},{is_valid}"
But as you said, it's an easy fix for the user to do themselves if they need it to be GGA.

2024-10-11 14:07 UTC, sindrehan commented
I don't have an actual device to test with, but I (CoPilot really) made a test script that uses an parser to check the validity and it seems to work fine with that.

```python
import socket
import pynmea2

# UDP configuration
UDP_IP = "0.0.0.0"
UDP_PORT = 10111

# Create a UDP socket
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sock.bind((UDP_IP, UDP_PORT))

print(f"Listening for UDP packets on {UDP_IP}:{UDP_PORT}")


def validate_nmea_sentence(sentence: str) -> bool:
    """Validate the NMEA sentence using pynmea2."""
    try:
        parsed_sentence = pynmea2.parse(sentence)
        return isinstance(parsed_sentence, pynmea2.types.talker.GLL)
    except pynmea2.nmea.ChecksumError:
        print("Checksum error")
        return False
    except pynmea2.nmea.ParseError:
        print("Parse error")
        return False


try:
    while True:
        data, addr = sock.recvfrom(1024)  # Buffer size is 1024 bytes
        message = data.decode("utf-8").strip()
        print(f"Received message: {message} from {addr}")

        if validate_nmea_sentence(message):
            print("Valid NMEA sentence")
        else:
            print("Invalid NMEA sentence")

except KeyboardInterrupt:
    print("Exiting...")
finally:
    sock.close()
```

2024-10-13 19:59 UTC, merged