Docs pictures
BluEye-Robotics/blueye.sdk pull request #91
Opened 2021-01-11 11:36 UTC by alexagv

**Description**
Update documentation for Blunux 1.8 features

#### Checklist before merging

- [ ] Run the tests while connected to a drone
- [ ] Update the package version according to [semver](https://semver.org/)

2021-01-11 14:36 UTC, alexagv commented
As discussed here: https://github.com/OAI/OpenAPI-Specification/issues/270
`oneOf` and `components` are used to describe multiple responses using the same return code

2021-01-11 22:08 UTC, sindrehan requested changes
Found a couple of copy-paste-errors that should be fixed, but other than that this looks good. 

We're approaching 1000 lines in this file, so we might need to look into if there are ways to structure it better, but that's out of scope for this PR.

2021-01-13 12:43 UTC, sindrehan approved these changes

2021-01-13 15:41 UTC, alexagv commented
Will merge once 1.8 is released

2021-05-06 09:19 UTC, merged